import logging
from typing import Dict, Any, Union
import json
import os
import google.generativeai as genai
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure Gemini API
api_key = os.getenv("GOOGLE_API_KEY")
if api_key:
    genai.configure(api_key=api_key)

logger = logging.getLogger("Auditor")

class Auditor:
    """
    The Auditor agent reviews the code generated by the Engineer.
    It acts as a "Agent-as-a-Judge" to ensure quality and safety.
    """

    def __init__(self, model_name: str = "gemini-2.5-flash"):
        self.model_name = model_name
        self.model = genai.GenerativeModel(model_name)
        logger.info(f"Auditor initialized with model: {model_name}")

    def review_code(self, code: str, blueprint: Dict[str, Any]) -> Union[bool, Dict[str, Any]]:
        """
        Reviews the code against the blueprint and safety guidelines.
        Returns True if approved, or a dictionary with feedback if rejected.
        """
        logger.info("Auditor reviewing code...")
        
        prompt = f"""
        You are The Auditor, a senior code reviewer.
        Review the following Python code generated for an AI agent.
        
        Blueprint:
        {blueprint}
        
        Code:
        {code}
        
        Checklist:
        1. Does the code implement the role and tools defined in the blueprint?
        2. Are there any security risks (e.g., unsafe imports like subprocess, os.system)?
        3. Is the code syntactically correct?
        4. Does it implement `max_api_calls`?
        5. Does it implement Context Compaction?
        
        Output a JSON object:
        {{
            "approved": true/false,
            "issues": ["List of issues if any"],
            "suggestions": ["List of suggestions for improvement"]
        }}
        """
        
        try:
            response = self.model.generate_content(prompt)
            text = response.text.strip()
            # Clean up markdown
            if text.startswith("```json"):
                text = text[7:]
            if text.startswith("```"):
                text = text[3:]
            if text.endswith("```"):
                text = text[:-3]
                
            result = json.loads(text.strip())
            
            if result.get("approved"):
                return True
            else:
                return result
        except Exception as e:
            logger.error(f"Error reviewing code: {e}")
            # Fail safe: reject if error
            return {"approved": False, "issues": [f"Auditor error: {e}"], "suggestions": ["Retry"]}
